In [ ]:
from ngio import open_ome_zarr_plate


In [4]:
from pathlib import Path

INPUT = Path(r"C:\Repos\sam_trainer\dat\test_zarr\exp164-diff0.zarr")

In [5]:
plate = open_ome_zarr_plate(INPUT)
print(plate)


Plate([rows x columns] (12 x 20))


In [7]:
image = plate.get_image(row="C", column=3, image_path="0")

In [ ]:
image_data = image.get_image()
arr = image_data.get_array()
type(arr)

In [20]:
well_i = plate.get_well_images

TypeError: OmeZarrPlate.get_well_images() missing 2 required positional arguments: 'row' and 'column'

In [29]:
ids = plate.get_wells().keys()
list(ids)[0][1:]

'/03'

In [32]:
id = list(ids)[0]
img = (
    plate.get_image(row=id[0], column=int(id[2:]), image_path="0")
    .get_image()
    .get_as_numpy()
)
img

array([[106, 116, 113, ..., 115, 104, 108],
       [101, 102, 111, ..., 108, 106, 113],
       [106, 109, 114, ..., 112, 112, 109],
       ...,
       [111, 115, 108, ..., 109, 116, 116],
       [107, 111, 104, ...,  99, 106, 108],
       [106,  99, 101, ..., 110, 105, 106]],
      shape=(2048, 2048), dtype=uint16)

In [43]:
from ngio.experimental.iterators import SegmentationIterator

# TODO load images in a loop here - loop over list(plate.get_wells().keys())
label = image.derive_label("sam_labels", overwrite=True)

seg = SegmentationIterator(input_image=image.get_image(), output_label=label)

# TODO add a loop over the wells here - get
for i, l in seg.iter_as_numpy():
    # TODO add the segmentation in this loop
    print(i, type(l))
    l(patch=img)

[[106 116 113 ... 115 104 108]
 [101 102 111 ... 108 106 113]
 [106 109 114 ... 112 112 109]
 ...
 [111 115 108 ... 109 116 116]
 [107 111 104 ...  99 106 108]
 [106  99 101 ... 110 105 106]] <class 'ngio.io_pipes._io_pipes_roi.NumpyRoiSetter'>
